### ISSUE TITLE
doesn't generate the same password

### ISSUE THREAD

**Issue by ec1oud** [peterh/pwdhash#1]
I have an Android version (installed from F-Droid) and there is the pwdhash.com web site, and this version: seems to me they all generate different passwords for the same domain/password combo. They aren't even the same length.  What am I missing?

Let's use 

$ pwdhash @@foobar http://www.example.com/

this Go version gives VGwPKA1Z, https://pwdhash.github.io/website/ (redirected from pwdhash.com) gives 4exCCMTka4, Password Hash on Android gives U+VXD3NS14

**Comment by peterh** [comment]
I get VGwPKA1Z from both Go and the website for @@foobar or foobar. 4exCCMTka4 is two characters too long, so it is definitely incorrect. I suspect a typo, or possibly another password manager interfering when you are using the website.

U+VXD3NSl4 is what you get from a literal @@foobar. Both the website and the go version strip the leading @@ for compatibility with the browser plugins that use @@ as a sigil to mean "hash this password".

Both the go version and the website give U+VXD3NS14 for @@@@foobar, and I suspect your Password Hash program would give VGwPKA1Z for foobar (without the leading @@).

Note that I no longer use pwdhash myself. I consider it only marginally better than re-using the same password without pwdhash.
